name: java-approach ci

on:
  push:
    paths:
      - 'java-approach/**'
  pull_request:
    paths:
      - 'java-approach/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14.0
      - name: Build
        run: mvn clean install
