on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14.0
      - name: Build Java project
        run: cd java-approach && mvn --batch-mode --update-snapshots verify
      - name: Set up node 14.15.5
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.5
      - name: Install JS dependencies
        run: cd javascript-approach && npm install
      - name: Run JS tests
        run: cd javascript-approach && npm run test:coverage
      - name: Upload to codecov
        uses: codecov/codecov-action@v1
